"use client";
import {useMemo,useState} from "react";
import {BarChart3,CalendarDays,ChevronLeft,ChevronRight,LayoutDashboard,Search,Sheet,Menu,RefreshCw} from "lucide-react";
import {Survey} from "@/lib/types";
const months=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
function sum(s:Survey){return s.months.reduce((a,m)=>({t:a.t+m.target,r:a.r+m.realization}),{t:0,r:0})}
function Calendar({surveys}:{surveys:Survey[]}){
 const [cursor,setCursor]=useState(new Date()); const y=cursor.getFullYear(), mo=cursor.getMonth();
 const first=new Date(y,mo,1).getDay(); const days=new Date(y,mo+1,0).getDate();
 const events=surveys.filter(s=>s.months[mo]?.target>0);
 return <section className="panel calendarPanel"><div className="panelHead"><div><p className="eyebrow">AGENDA KEGIATAN</p><h2>Kalender {months[mo]} {y}</h2></div><div className="calNav"><button onClick={()=>setCursor(new Date(y,mo-1,1))}><ChevronLeft/></button><button onClick={()=>setCursor(new Date())}>Hari ini</button><button onClick={()=>setCursor(new Date(y,mo+1,1))}><ChevronRight/></button></div></div><div className="calendar"><div className="week">{["Min","Sen","Sel","Rab","Kam","Jum","Sab"].map(d=><b key={d}>{d}</b>)}</div><div className="days">{Array.from({length:first}).map((_,i)=><span className="blank" key={'b'+i}/>)}{Array.from({length:days},(_,i)=>i+1).map(d=><div className={d===new Date().getDate()&&mo===new Date().getMonth()?"day today":"day"} key={d}><span>{d}</span>{events.slice(0,2).map((e,j)=><i key={e.id} className={'event e'+j} title={e.name}>{e.name.slice(0,18)}</i>)}</div>)}</div></div></section>
}
export default function Dashboard({initial,source}:{initial:Survey[];source:string}){
 const [view,setView]=useState<'dashboard'|'calendar'>('dashboard'); const [q,setQ]=useState('');
 const filtered=useMemo(()=>initial.filter(s=>(s.name+s.category+s.owner).toLowerCase().includes(q.toLowerCase())),[initial,q]);
 const totals=filtered.reduce((a,s)=>{const x=sum(s);a.t+=x.t;a.r+=x.r;return a},{t:0,r:0}); const pct=totals.t?Math.round(totals.r/totals.t*100):0;
 const cards=filtered.slice(0,5);
 return <div className="shell"><aside><div className="brand"><span>SI</span></div><button className={view==='dashboard'?'active':''} onClick={()=>setView('dashboard')} title="Dashboard"><LayoutDashboard/></button><button className={view==='calendar'?'active':''} onClick={()=>setView('calendar')} title="Kalender"><CalendarDays/></button><button title="Sumber spreadsheet"><Sheet/></button><div className="spacer"/><small>v1.0</small></aside><main><header><button className="icon"><Menu/></button><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari kegiatan, kategori, atau tim..."/></div><div className="source"><span></span>{source}</div><div className="avatar">JK</div></header><div className="content">{view==='calendar'?<Calendar surveys={filtered}/>:<><section className="hero"><div><p className="eyebrow">SISTEM MONITORING TERPADU</p><h1>Ringkasan Kegiatan Survei</h1><p>Pantau Target, Realisasi, dan Agenda dari satu Dashboard.</p></div><div className="heroStat"><BarChart3/><div><b>{pct}%</b><span>Capaian keseluruhan</span></div></div></section><section className="metrics"><article><span>Total target</span><b>{totals.t}</b><small>Seluruh Periode</small></article><article><span>Realisasi</span><b>{totals.r}</b><small>Data Terkumpul</small></article><article><span>Kegiatan Aktif</span><b>{filtered.length}</b><small>Lintas Kategori</small></article><article><span>Sisa Target</span><b>{Math.max(0,totals.t-totals.r)}</b><small>Perlu diTindaklanjuti</small></article></section><section className="cards">{cards.map((s,i)=>{const x=sum(s),p=x.t?Math.min(100,Math.round(x.r/x.t*100)):0;return <article className="surveyCard" key={s.id}><div className="cardTop"><span>{s.category}</span><em>{s.period}</em></div><h3>{s.name}</h3><div className="big"><b>{p}%</b><small>{x.r} dari {x.t} target</small></div><div className="progress"><i style={{width:p+'%'}}/></div><footer><span>Belum: {Math.max(0,x.t-x.r)}</span><span className="done">Selesai: {x.r}</span></footer></article>})}</section><section className="panel"><div className="panelHead"><div><p className="eyebrow">MONITORING BULANAN</p><h2>Target dan Realisasi</h2></div><button className="soft"><RefreshCw/> Sinkron 5 menit</button></div><div className="tableWrap"><table><thead><tr><th rowSpan={2}>Kegiatan survei</th><th rowSpan={2}>Periode</th>{months.map(m=><th colSpan={2} key={m}>{m.slice(0,3)}</th>)}</tr><tr>{months.flatMap(m=>[<th key={m+'t'}>T</th>,<th key={m+'r'}>R</th>])}</tr></thead><tbody>{filtered.map((s,idx)=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.category} · {s.owner}</small></td><td>{s.period}</td>{s.months.flatMap((m,i)=>[<td key={i+'t'} className={m.target?'target':''}>{m.target||''}</td>,<td key={i+'r'} className={m.realization?(m.realization>=m.target?'ok':'warn'):''}>{m.realization||''}</td>])}</tr>)}</tbody></table></div></section></>}</div></main></div>
}
